// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Service, Status } from './app.service';

import validationEngine from "devextreme/ui/validation_engine";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [Service]
})
export class AppComponent {
  employee: any;
  editorOptions: object;
  statuses: Status[];

  constructor(service: Service) {
    this.employee = {
        owner: "John Heart",
        status: 1
    }

    this.statuses = service.getStatuses();
  }

  validateClick(){
    let validationResult = validationEngine.validateGroup("formGroup");

    if (!validationResult.isValid)
        alert("dxForm is invalid");
  }
}

<dx-form [formData]="employee" validationGroup="formGroup">
  <dxi-item dataField="owner">
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-item>
  <dxi-item dataField="status" template="statusTemplate"></dxi-item>
  <dxi-item itemType="button" horizontalAlignment="left"
    [buttonOptions]="{ text: 'Validate', type: 'success', onClick: validateClick }"></dxi-item>

  <div *dxTemplate="let cellInfo of 'statusTemplate'">
    <dx-drop-down-box [dataSource]="statuses" [(value)]="employee.status" [showClearButton]="true" valueExpr="id"
      displayExpr="name">
      <div *dxTemplate="let data of 'content'">
        <dx-data-grid [dataSource]="statuses" [height]="250" keyExpr="id" [(selectedRowKeys)]="employee.status">
          <dxo-selection mode="single"></dxo-selection>
        </dx-data-grid>
      </div>
      <dx-validator validationGroup="formGroup">
        <dxi-validation-rule type="required" message="Status is required">
        </dxi-validation-rule>
      </dx-validator>
    </dx-drop-down-box>
  </div>
</dx-form>

// Vue/src/App.vue
<template>
  <DxForm :form-data="employee" validation-group="formGroup">
      <DxItem data-field="Owner" />
      <DxItem data-field="Status" :is-required="true" template="statusTemplate" />
      <DxItem item-type="button" horizontal-alignment="left"
        :button-options="{ text: 'Validate', type: 'success', onClick: validateClick }" />

      <template #statusTemplate>
        <DxDropDownBox
          :data-source="statuses"
          :value.sync="employee.Status"
          :show-clear-button="true"
          value-expr="Id"
          display-expr="Name"
        >
          <template #content>
            <DxDataGrid
              :data-source="statuses"
              :height="250"
              key-expr="Id"
              :selected-row-keys.sync="employee.Status"
            >
              <DxSelection mode="single"/>
            </DxDataGrid>
          </template>

          <DxValidator validation-group="formGroup">
            <DxRequiredRule message="Status is required"/>
          </DxValidator>
        </DxDropDownBox>
      </template>
    </DxForm>
</template>

<script>
import { DxForm, DxItem } from 'devextreme-vue/form';
import DxDropDownBox from 'devextreme-vue/drop-down-box';
import { DxDataGrid, DxSelection } from 'devextreme-vue/data-grid';
import {
  DxValidator,
  DxRequiredRule,
} from 'devextreme-vue/validator';
import validationEngine from "devextreme/ui/validation_engine";
import service from './data.js';

export default  {
  name: "App",
  components: {
    DxForm,
    DxItem,
    DxValidator,
    DxRequiredRule,
    DxDataGrid, 
    DxSelection,
    DxDropDownBox
  },
  data() {
    return {
      employee: service.getEmployee(),
      statuses: service.getStatuses()
    };
  },
  methods: {
    validateClick() {
      let validationResult = validationEngine.validateGroup("formGroup");
      if (!validationResult.isValid)
          alert("dxForm is invalid");
      }
  }
};
</script>
